DROP SCHEMA IF EXISTS BRAINIAC CASCADE;

CREATE SCHEMA BRAINIAC;

CREATE TABLE USERS(
  N_USER_ID 		SERIAL	PRIMARY KEY,
  N_VK_ID 			INT 		NOT NULL,
  VC_FIRST_NAME VARCHAR NOT NULL,
  VC_LAST_NAME 	VARCHAR NOT NULL,
  N_MAX_STEP 		INT 							DEFAULT '1',
  B_ACTIVE			BOOL,
  N_TOTAL_SCORE INT
);

CREATE TABLE STEPS(
	N_STEP_ID 		SERIAL 	PRIMARY KEY,
	N_STEP_NUMBER INT 		NOT NULL,
	VC_STEP_DESC 	VARCHAR
);

CREATE TABLE QUESTIONS(
	N_QUESTION_ID SERIAL 		PRIMARY KEY,
  N_STEP_ID 		INT 			NOT NULL 		REFERENCES STEPS (N_STEP_ID),
  N_STEP_NUMBER INT				NOT NULL,
  N_NUMBER 			INT 			NOT NULL,
  VC_TYPE 			VARCHAR 	NOT NULL,
  VC_TEXT 			VARCHAR,
  D_TIME_START  TIMESTAMP NOT NULL,
  D_TIME_STOP 	TIMESTAMP NOT NULL,
  B_PIC 				BOOL
);

CREATE TABLE ANSWERS (
  N_ANSWER_ID 	SERIAL 		PRIMARY KEY,
  N_QUESTION_ID INT 	 		NOT NULL REFERENCES QUESTIONS (N_QUESTION_ID),
  N_USER_ID			INT 	 		NOT NULL REFERENCES USERS (N_USER_ID),
  N_SCORES			INT 	  	NOT NULL,
  VC_ANSWER 		VARCHAR,
  D_TIME 				TIMESTAMP	DEFAULT NOW()
);

CREATE TABLE PARAMETERS (
  N_PARAMETER_ID 		SERIAL 	PRIMARY KEY,
  VC_PARAMETER_CODE VARCHAR NOT NULL,
  VC_VALUE			 		VARCHAR,
  N_VALUE        		INT
);

CREATE TABLE PRICES(
	N_PRICE_ID 		 SERIAL	PRIMARY KEY,
	N_QUESTION_ID  INT 		NOT NULL REFERENCES QUESTIONS (N_QUESTION_ID),
	N_BONUS_COUNT  INT 		NOT NULL,
	N_BONUS_PRICE  INT 		NOT NULL,
	N_NORMAL_PRICE INT 		NOT NULL
);

CREATE TABLE TRUE_ANSWERS(
	N_TRUE_ANSWER_ID SERIAL	 					PRIMARY KEY,
  N_QUESTION_ID  	 INT 		 NOT NULL REFERENCES QUESTIONS (N_QUESTION_ID),
  VC_TRUE_ANSWER 	 VARCHAR NOT NULL
);

CREATE TABLE SESSIONS(
	N_SESSION_ID 		SERIAL 		PRIMARY KEY,
	VC_SESSION_KEY 	VARCHAR 	NOT NULL,
	N_USER_ID     	INT 			NOT NULL,
	VC_ACCESS_TOKEN VARCHAR 	NOT NULL,
	D_TIME_START  	TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX session_index ON SESSIONS(VC_SESSION_KEY);
CREATE UNIQUE INDEX n_vk_id_idx ON USERS(N_VK_ID);

INSERT INTO PARAMETERS(VC_PARAMETER_CODE, VC_VALUE) VALUES ('rules', '');
INSERT INTO PARAMETERS(VC_PARAMETER_CODE, VC_VALUE) VALUES ('about', '');
INSERT INTO PARAMETERS(VC_PARAMETER_CODE, VC_VALUE) VALUES ('admins', '');--Insert your VK-id here

COMMIT;
